### ISSUE TITLE
Exception when using Fulltext search

### ISSUE THREAD

**Issue by sibeon** [palle1977/SMT#8]
When using the Fulltextsearch I get an exception:

`
Fatal error: Uncaught exception 'PHPTAL_VariableNotFoundException' with message 'Unable to find variable 'list_art' in current scope' in /var/www/html/template/inventory/search.xhtml:8 Stack trace: #0 /tmp/tpl_58395a46_search__QeSS6rcwO5ACDfhfrsnMvg.php(35): PHPTAL_Context->__get('list_art') #1 /var/www/html/library/App/Plugins/PHPTAL.php(767): tpl_58395a46_search__QeSS6rcwO5ACDfhfrsnMvg_standard(Object(PHPTAL), Object(PHPTAL)) #2 /tmp/tpl_58395a43_inventory__3ljg2B7qsSVLDRf7liravQ.php(40): PHPTAL->_executeMacroOfTemplate('inventory/searc...', Object(PHPTAL)) #3 /var/www/html/library/App/Plugins/PHPTAL.php(669): tpl_58395a43_inventory__3ljg2B7qsSVLDRf7liravQ(Object(PHPTAL), Object(PHPTAL_Context)) #4 /var/www/html/library/App/Template.php(130): PHPTAL->execute() #5 /var/www/html/library/App/Template.php(123): Template->showTemplate() #6 /var/www/html/library/App/Template.php(36): Template->showOuput() #7 /var/www/html/library/App/Content.php(33): Template->__construct() #8 /var/www/html/library/App/Base.php(32): Content-> in /var/www/html/template/inventory/search.xhtml on line 8`

I am using v1.3.2

**Comment by palle1977** [comment]
This will be fixed with a new feature, on the entry page of the inventory, all tables from inventory should be searched.
